package com.excel.demo.mapper;

import com.excel.demo.model.FansInfo;
import java.util.List;

public interface FansInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fansinfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fansinfo
     *
     * @mbg.generated
     */
    int insert(FansInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fansinfo
     *
     * @mbg.generated
     */
    FansInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fansinfo
     *
     * @mbg.generated
     */
    List<FansInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fansinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FansInfo record);
    
    /**
     * This method was generated by Terry.
     * This method corresponds to the database table t_fansinfo
     *
     * @mbg.generated
     */
    List<FansInfo> selectAllByUserId(Integer userId);
}