package com.excel.demo.model;

import java.io.Serializable;

public class FansInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fansinfo.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fansinfo.fans_code
     *
     * @mbg.generated
     */
    private String fansCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fansinfo.fans_name
     *
     * @mbg.generated
     */
    private String fansName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fansinfo.fans_rmk
     *
     * @mbg.generated
     */
    private String fansRmk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fansinfo.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_fansinfo
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fansinfo.id
     *
     * @return the value of t_fansinfo.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fansinfo.id
     *
     * @param id the value for t_fansinfo.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fansinfo.fans_code
     *
     * @return the value of t_fansinfo.fans_code
     *
     * @mbg.generated
     */
    public String getFansCode() {
        return fansCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fansinfo.fans_code
     *
     * @param fansCode the value for t_fansinfo.fans_code
     *
     * @mbg.generated
     */
    public void setFansCode(String fansCode) {
        this.fansCode = fansCode == null ? null : fansCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fansinfo.fans_name
     *
     * @return the value of t_fansinfo.fans_name
     *
     * @mbg.generated
     */
    public String getFansName() {
        return fansName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fansinfo.fans_name
     *
     * @param fansName the value for t_fansinfo.fans_name
     *
     * @mbg.generated
     */
    public void setFansName(String fansName) {
        this.fansName = fansName == null ? null : fansName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fansinfo.fans_rmk
     *
     * @return the value of t_fansinfo.fans_rmk
     *
     * @mbg.generated
     */
    public String getFansRmk() {
        return fansRmk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fansinfo.fans_rmk
     *
     * @param fansRmk the value for t_fansinfo.fans_rmk
     *
     * @mbg.generated
     */
    public void setFansRmk(String fansRmk) {
        this.fansRmk = fansRmk == null ? null : fansRmk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fansinfo.user_id
     *
     * @return the value of t_fansinfo.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fansinfo.user_id
     *
     * @param userId the value for t_fansinfo.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fansinfo
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", fansCode=").append(fansCode);
        sb.append(", fansName=").append(fansName);
        sb.append(", fansRmk=").append(fansRmk);
        sb.append(", userId=").append(userId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}