package com.excel.demo.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class FilmFocus implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_filmfocus.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_filmfocus.film_code
     *
     * @mbg.generated
     */
    private String filmCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_filmfocus.film_name
     *
     * @mbg.generated
     */
    private String filmName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_filmfocus.film_actors
     *
     * @mbg.generated
     */
    private String filmActors;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_filmfocus.film_show_date
     *
     * @mbg.generated
     */
    private Date filmShowDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_filmfocus.film_price
     *
     * @mbg.generated
     */
    private BigDecimal filmPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_filmfocus.film_rmk
     *
     * @mbg.generated
     */
    private String filmRmk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_filmfocus.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_filmfocus
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_filmfocus.id
     *
     * @return the value of t_filmfocus.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_filmfocus.id
     *
     * @param id the value for t_filmfocus.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_filmfocus.film_code
     *
     * @return the value of t_filmfocus.film_code
     *
     * @mbg.generated
     */
    public String getFilmCode() {
        return filmCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_filmfocus.film_code
     *
     * @param filmCode the value for t_filmfocus.film_code
     *
     * @mbg.generated
     */
    public void setFilmCode(String filmCode) {
        this.filmCode = filmCode == null ? null : filmCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_filmfocus.film_name
     *
     * @return the value of t_filmfocus.film_name
     *
     * @mbg.generated
     */
    public String getFilmName() {
        return filmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_filmfocus.film_name
     *
     * @param filmName the value for t_filmfocus.film_name
     *
     * @mbg.generated
     */
    public void setFilmName(String filmName) {
        this.filmName = filmName == null ? null : filmName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_filmfocus.film_actors
     *
     * @return the value of t_filmfocus.film_actors
     *
     * @mbg.generated
     */
    public String getFilmActors() {
        return filmActors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_filmfocus.film_actors
     *
     * @param filmActors the value for t_filmfocus.film_actors
     *
     * @mbg.generated
     */
    public void setFilmActors(String filmActors) {
        this.filmActors = filmActors == null ? null : filmActors.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_filmfocus.film_show_date
     *
     * @return the value of t_filmfocus.film_show_date
     *
     * @mbg.generated
     */
    public Date getFilmShowDate() {
        return filmShowDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_filmfocus.film_show_date
     *
     * @param filmShowDate the value for t_filmfocus.film_show_date
     *
     * @mbg.generated
     */
    public void setFilmShowDate(Date filmShowDate) {
        this.filmShowDate = filmShowDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_filmfocus.film_price
     *
     * @return the value of t_filmfocus.film_price
     *
     * @mbg.generated
     */
    public BigDecimal getFilmPrice() {
        return filmPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_filmfocus.film_price
     *
     * @param filmPrice the value for t_filmfocus.film_price
     *
     * @mbg.generated
     */
    public void setFilmPrice(BigDecimal filmPrice) {
        this.filmPrice = filmPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_filmfocus.film_rmk
     *
     * @return the value of t_filmfocus.film_rmk
     *
     * @mbg.generated
     */
    public String getFilmRmk() {
        return filmRmk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_filmfocus.film_rmk
     *
     * @param filmRmk the value for t_filmfocus.film_rmk
     *
     * @mbg.generated
     */
    public void setFilmRmk(String filmRmk) {
        this.filmRmk = filmRmk == null ? null : filmRmk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_filmfocus.user_id
     *
     * @return the value of t_filmfocus.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_filmfocus.user_id
     *
     * @param userId the value for t_filmfocus.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_filmfocus
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", filmCode=").append(filmCode);
        sb.append(", filmName=").append(filmName);
        sb.append(", filmActors=").append(filmActors);
        sb.append(", filmShowDate=").append(filmShowDate);
        sb.append(", filmPrice=").append(filmPrice);
        sb.append(", filmRmk=").append(filmRmk);
        sb.append(", userId=").append(userId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}